// 아이템 설명을 수동으로 관리하는 파일입니다.
// apiName 또는 id를 키(Key)로 사용하고, 설명 텍스트를 값(Value)으로 입력하세요.
export const ITEM_DESCRIPTIONS = {
  // ==========================================================================================
  // 1. 재료 아이템 (Components)
  // ==========================================================================================
  "TFT_Item_BFSword": "%i:scaleAD% 공격력 +10%",
  "TFT_Item_RecurveBow": "%i:scaleSpeed% 공격 속도 +10%",
  "TFT_Item_NeedlesslyLargeRod": "%i:scaleAP% 주문력 +10",
  "TFT_Item_TearOfTheGoddess": "%i:scaleMana% 마나 +15",
  "TFT_Item_ChainVest": "%i:scaleArmor% 방어력 +20",
  "TFT_Item_NegatronCloak": "%i:scaleMR% 마법 저항력 +20",
  "TFT_Item_GiantsBelt": "%i:scaleHealth% 체력 +150",
  "TFT_Item_Spatula": "다양한 특성 상징을 만들 수 있습니다.",
  "TFT_Item_SparringGloves": "%i:scaleCrit% 치명타 확률 +20%",

  // ==========================================================================================
  // 2. 완성 아이템 (Completed Items)
  // ==========================================================================================
  "TFT_Item_Bloodthirster": "%i:scaleAD% 공격력 +15%, %i:scaleAP% 주문력 +15, %i:scaleMR% 마법 저항력 +20. 모든 피해 흡혈 +20%. 체력이 40% 아래로 떨어지면 최대 체력의 25%에 해당하는 보호막을 얻습니다.",
  "TFT_Item_BrambleVest": "%i:scaleArmor% 방어력 +55. 받는 치명타 피해량이 8% 감소합니다. 기본 공격을 받으면 인접한 적에게 마법 피해를 입힙니다.",
  "TFT_Item_Deathblade": "%i:scaleAD% 공격력 +50%. 추가 피해량 8% 증가.",
  "TFT_Item_DragonsClaw": "%i:scaleMR% 마법 저항력 +65, %i:scaleHealth% 체력 +150. 2초마다 최대 체력의 5%를 회복합니다.",
  "TFT_Item_ThiefsGloves": "%i:scaleCrit% 치명타 확률 +20%, %i:scaleHealth% 체력 +150. 매 라운드 무작위 아이템 2개를 장착합니다.",
  "TFT_Item_FrozenHeart": "%i:scaleMana% 마나 +30, %i:scaleArmor% 방어력 +20. 전투 시작 시 40% 체력 이하가 되면 5초 동안 최대 체력의 25% 보호막을 얻고 방어력과 마법 저항력이 35 증가합니다. (수호자의 맹세)",
  "TFT_Item_MadredsBloodrazor": "%i:scaleAD% 공격력 +30%, %i:scaleAP% 주문력 +20%, %i:scaleSpeed% 공격 속도 +10%. 체력이 1600보다 많은 적에게 25%의 추가 피해를 입힙니다. (거인 학살자)",
  "TFT_Item_GuardianAngel": "%i:scaleAD% 공격력 +10%, %i:scaleArmor% 방어력 +20. 전투당 한 번 체력이 60% 아래로 떨어지면 잠시 동안 지정할 수 없는 상태가 되며 해로운 효과를 제거합니다. (밤의 끝자락)",
  "TFT_Item_GuinsoosRageblade": "%i:scaleSpeed% 공격 속도 +15%, %i:scaleAP% 주문력 +10. 공격 시 공격 속도가 5% 증가합니다. (무제한 중첩)",
  "TFT_Item_UnstableConcoction": "%i:scaleMana% 마나 +15, %i:scaleCrit% 치명타 확률 +20%. 공격력/주문력 15% 증가 및 모든 피해 흡혈 10% 증가. 라운드마다 두 효과 중 하나가 2배로 적용됩니다. (정의의 손길)",
  "TFT_Item_InfinityEdge": "%i:scaleAD% 공격력 +35%, %i:scaleCrit% 치명타 확률 +35%. 스킬에 치명타가 적용될 수 있습니다.",
  "TFT_Item_IonicSpark": "%i:scaleAP% 주문력 +15, %i:scaleMR% 마법 저항력 +25, %i:scaleHealth% 체력 +150. 2칸 내 적의 마법 저항력을 30% 감소시킵니다. 해당 적이 스킬을 쓰면 마법 피해를 입힙니다.",
  "TFT_Item_JeweledGauntlet": "%i:scaleAP% 주문력 +30, %i:scaleCrit% 치명타 확률 +35%. 스킬에 치명타가 적용될 수 있습니다.",
  "TFT_Item_LastWhisper": "%i:scaleAD% 공격력 +15%, %i:scaleSpeed% 공격 속도 +20%, %i:scaleCrit% 치명타 확률 +20%. 물리 피해를 입히면 3초 동안 대상의 방어력을 30% 감소시킵니다.",
  "TFT_Item_ArchangelsStaff": "%i:scaleAP% 주문력 +20, %i:scaleMana% 마나 +15. 전투 시작 시 주문력이 10 증가하며, 5초마다 주문력이 20씩 증가합니다.",
  "TFT_Item_Quicksilver": "%i:scaleMR% 마법 저항력 +30, %i:scaleSpeed% 공격 속도 +30%, %i:scaleCrit% 치명타 확률 +20%. 전투 시작 시 14초 동안 군중 제어 효과에 면역이 됩니다.",
  "TFT_Item_Morellonomicon": "%i:scaleAP% 주문력 +25, %i:scaleSpeed% 공격 속도 +10%, %i:scaleHealth% 체력 +150. 스킬 및 기본 공격으로 피해를 입히면 10초 동안 대상을 불태워 매초 1% 고정 피해를 입히고 치유 효과를 33% 감소시킵니다.",
  "TFT_Item_PowerGauntlet": "%i:scaleAD% 공격력 +10%, %i:scaleAP% 주문력 +20%, %i:scaleSpeed% 공격 속도 +20%, %i:scaleCrit% 치명타 확률 +20%. 보호막을 가진 적 공격 시 3초 동안 피해량이 25% 증가합니다. (타격대의 철퇴)",
  "TFT_Item_RabadonsDeathcap": "%i:scaleAP% 주문력 +50. 추가 피해량 20% 증가.",
  "TFT_Item_RapidFireCannon": "%i:scaleSpeed% 공격 속도 +40%. 피해를 입히면 5초 동안 대상을 불태워 1% 고정 피해를 입히고 치유 효과를 33% 감소시킵니다. (붉은 덩굴정령)",
  "TFT_Item_RedBuff": "%i:scaleHealth% 체력 +150, %i:scaleArmor% 방어력 +20. 2초마다 범위 내 적에게 10초 동안 최대 체력의 10%만큼 고정 피해를 입히고 치유 효과를 33% 감소시킵니다. (태양불꽃 망토)",
  "TFT_Item_Redemption": "정령의 형상",
  "TFT_Item_RunaansHurricane": "크라켄의 분노",
  "TFT_Item_SpearOfShojin": "%i:scaleAD% 공격력 +15%, %i:scaleAP% 주문력 +15, %i:scaleMana% 마나 +15. 공격 시 마나를 5 추가로 회복합니다.",
  "TFT_Item_StatikkShiv": "공허의 지팡이",
  "TFT_Item_GargoyleStoneplate": "%i:scaleArmor% 방어력 +30, %i:scaleMR% 마법 저항력 +30, %i:scaleHealth% 체력 +100. 공격하는 적 하나당 방어력/마법 저항력 10 증가.",
  "TFT_Item_TitanicHydra": "즈롯 차원문",
  "TFT_Item_TitansResolve": "%i:scaleSpeed% 공격 속도 +10%, %i:scaleArmor% 방어력 +20. 공격하거나 피해를 입으면 공격력 2%, 주문력 2가 증가합니다. (최대 25회 중첩)",
  "TFT_Item_WarmogsArmor": "%i:scaleHealth% 체력 +600, %i:scaleHealth% 최대 체력 +8%.",
  "TFT_Item_SpectralGauntlet": "%i:scaleHealth% 체력 +150, %i:scaleMR% 마법 저항력 +20. 2칸 내 적의 방어력을 30% 감소시킵니다. 전투 시작 시 10초 동안 방어력과 마법 저항력이 25 증가합니다. (저녁갑주)",
  "TFT_Item_Crownguard": "%i:scaleAP% 주문력 +20, %i:scaleArmor% 방어력 +20, %i:scaleHealth% 체력 +250. 전투 시작 시 8초 동안 최대 체력의 30%에 해당하는 보호막을 얻습니다. 보호막 파괴 시 주문력이 40 증가합니다.",
  "TFT_Item_NightHarvester": "%i:scaleHealth% 체력 +200, %i:scaleArmor% 방어력 +20, %i:scaleCrit% 치명타 확률 +20%. 받는 피해량 8% 감소합니다. 체력이 50% 이상일 때 감소량이 15%로 증가합니다. (굳건한 심장)",
  "TFT_Item_SteraksGage": "%i:scaleHealth% 체력 +150, %i:scaleAD% 공격력 +15%. 전투당 한 번 체력이 60% 아래로 떨어지면 최대 체력 25%의 추가 체력과 공격력 35%를 얻습니다.",
  "TFT_Item_BlueBuff": "%i:scaleAD% 공격력 +20, %i:scaleAP% 주문력 +20, %i:scaleMana% 마나 +20. 최대 마나가 10 감소합니다. 적 처치 관여 시 8초 동안 피해량이 8% 증가합니다. (푸른 파수꾼)",
  "TFT_Item_AdaptiveHelm": "%i:scaleMana% 마나 +15, %i:scaleAP% 주문력 +15, %i:scaleMR% 마법 저항력 +20. 전방: 방어/마저 증가. 후방: 주문력 증가 및 마나 회복.",
  "TFT_Item_Leviathan": "%i:scaleAP% 주문력 +30, %i:scaleSpeed% 공격 속도 +10%, %i:scaleHealth% 체력 +150. 스킬 사용 시 5초 동안 공격 속도가 40% 증가합니다. (내셔의 이빨)",

  // ==========================================================================================
  // 3. 찬란한 아이템 (Radiant Items)
  // ==========================================================================================
  "TFT5_Item_TrapClawRadiant": "찬란한 타격대의 철퇴",
  "TFT5_Item_BloodthirsterRadiant": "찬란한 피바라기",
  "TFT5_Item_IonicSparkRadiant": "찬란한 이온 충격기",
  "TFT5_Item_GiantSlayerRadiant": "찬란한 거인 학살자",
  "TFT5_Item_DragonsClawRadiant": "찬란한 용의 발톱",
  "TFT5_Item_GargoyleStoneplateRadiant": "찬란한 가고일 돌갑옷",
  "TFT5_Item_LastWhisperRadiant": "찬란한 최후의 속삭임",
  "TFT5_Item_HandOfJusticeRadiant": "찬란한 정의의 손길",
  "TFT5_Item_FrozenHeartRadiant": "찬란한 수호자의 맹세",
  "TFT5_Item_JeweledGauntletRadiant": "찬란한 보석 건틀릿",
  "TFT5_Item_GuardianAngelRadiant": "찬란한 밤의 끝자락",
  "TFT5_Item_GuinsoosRagebladeRadiant": "찬란한 구인수의 격노검",
  "TFT5_Item_HextechGunbladeRadiant": "찬란한 마법공학 총검",
  "TFT5_Item_DeathbladeRadiant": "찬란한 죽음의 검",
  "TFT5_Item_MorellonomiconRadiant": "찬란한 모렐로노미콘",
  "TFT5_Item_QuicksilverRadiant": "찬란한 수은",
  "TFT5_Item_RabadonsDeathcapRadiant": "찬란한 라바돈의 죽음모자",
  "TFT5_Item_RedemptionRadiant": "찬란한 정령의 형상",
  "TFT5_Item_RapidFirecannonRadiant": "찬란한 붉은 덩굴정령",
  "TFT5_Item_ThiefsGlovesRadiant": "찬란한 도적의 장갑",
  "TFT5_Item_BrambleVestRadiant": "찬란한 덤불 조끼",
  "TFT5_Item_RunaansHurricaneRadiant": "찬란한 크라켄의 분노",
  "TFT5_Item_SpearOfShojinRadiant": "찬란한 쇼진의 창",
  "TFT5_Item_StatikkShivRadiant": "찬란한 공허의 지팡이",
  "TFT5_Item_SunfireCapeRadiant": "찬란한 태양불꽃 망토",
  "TFT5_Item_TitansResolveRadiant": "찬란한 거인의 결의",
  "TFT5_Item_ArchangelsStaffRadiant": "찬란한 대천사의 지팡이",
  "TFT5_Item_WarmogsArmorRadiant": "찬란한 워모그의 갑옷",
  "TFT5_Item_InfinityEdgeRadiant": "찬란한 무한의 대검",
  "TFT5_Item_SpectralGauntletRadiant": "찬란한 저녁갑주",
  "TFT5_Item_CrownguardRadiant": "찬란한 크라운가드",
  "TFT5_Item_NightHarvesterRadiant": "찬란한 굳건한 심장",
  "TFT5_Item_SteraksGageRadiant": "찬란한 스테락의 도전",
  "TFT5_Item_BlueBuffRadiant": "찬란한 푸른 파수꾼",
  "TFT5_Item_AdaptiveHelmRadiant": "찬란한 적응형 투구",
  "TFT5_Item_LeviathanRadiant": "찬란한 내셔의 이빨",

  // ==========================================================================================
  // 4. 유물 아이템 (Artifact Items)
  // ==========================================================================================
  "TFT4_Item_OrnnDeathsDefiance": "죽음의 저항",
  "TFT4_Item_OrnnTheCollector": "황금 징수의 총",
  "TFT4_Item_OrnnInfinityForce": "무한한 삼위일체",
  "TFT4_Item_OrnnMuramana": "마나자네",
  "TFT4_Item_OrnnZhonyasParadox": "존야의 역설",
  "TFT9_Item_OrnnHullbreaker": "선체분쇄자",
  "TFT9_Item_OrnnHorizonFocus": "저격수의 집중",
  "TFT_Item_Artifact_TalismanOfAscension": "승천의 부적",
  "TFT_Item_Artifact_Fishbones": "생선대가리",
  "TFT_Item_Artifact_HorizonFocus": "지평선의 초점",
  "TFT_Item_Artifact_Mittens": "방한 장갑",
  "TFT_Item_Artifact_RapidFirecannon": "고속 연사포",
  "TFT_Item_Artifact_LudensTempest": "루덴의 폭풍",
  "TFT_Item_Artifact_SilvermereDawn": "은빛 여명",
  "TFT_Item_Artifact_ProwlersClaw": "자객의 발톱",
  "TFT_Item_Artifact_BlightingJewel": "역병의 보석",
  "TFT_Item_Artifact_WitsEnd": "마법사의 최후",
  "TFT_Item_Artifact_LichBane": "리치베인",
  "TFT_Item_Artifact_LightshieldCrest": "라이트실드 문장",
  "TFT_Item_Artifact_SeekersArmguard": "추적자의 팔목 보호대",
  "TFT_Item_Artifact_NavoriFlickerblades": "명멸검",
  "TFT_Item_Artifact_StatikkShiv": "스태틱의 단검",
  "TFT_Item_Artifact_TheIndomitable": "불굴",
  "TFT_Item_Artifact_Dawncore": "새벽심장",
  "TFT_Item_Artifact_TitanicHydra": "거대한 히드라",
  "TFT_Item_Artifact_HellfireHatchet": "지옥불 손도끼",
  "TFT_Item_Artifact_CappaJuice": "카파 주스",
  "TFT_Item_Artifact_EternalPact": "영원한 서약",
  "TFT_Item_Artifact_VoidGauntlet": "공허 건틀릿",
  "TFT_Item_Artifact_AegisOfDawn": "새벽의 방패",
  "TFT_Item_Artifact_AegisOfDusk": "황혼의 방패",

  // ==========================================================================================
  // 5. 특성 및 상징 (Traits & Emblems)
  // ==========================================================================================
  "TFT16_Item_Bilgewater_BilgeratCutlass": "불한당의 해적검",
  "TFT16_Item_Bilgewater_BlackmarketExplosives": "암시장 폭발물",
  "TFT16_Item_Bilgewater_DeadmansDagger": "망자의 단검",
  "TFT16_Item_Bilgewater_PileOCitrus": "귤 더미",
  "TFT16_Item_BilgewaterEmblemItem": "빌지워터 상징",
  "TFT16_Item_BrawlerEmblemItem": "난동꾼 상징",
  "TFT16_Item_DefenderEmblemItem": "엄호대 상징",
  "TFT16_Item_DemaciaEmblemItem": "데마시아 상징",
  "TFT16_Item_FreljordEmblemItem": "프렐요드 상징",
  "TFT16_Item_GunslingerEmblemItem": "총잡이 상징",
  "TFT16_Item_InvokerEmblemItem": "기원자 상징",
  "TFT16_Item_IoniaEmblemItem": "아이오니아 상징",
  "TFT16_Item_JuggernautEmblemItem": "전쟁기계 상징",
  "TFT16_Item_LongshotEmblemItem": "원거리 사격 상징",
  "TFT16_Item_MagusEmblemItem": "방해꾼 상징",
  "TFT16_Item_NoxusEmblemItem": "녹서스 상징",
  "TFT16_Item_PiltoverEmblemItem": "필트오버 상징",
  "TFT16_Item_RapidfireEmblemItem": "기동타격대 상징",
  "TFT16_Item_SorcererEmblemItem": "비전 마법사 상징",
  "TFT16_Item_VanquisherEmblemItem": "토벌자 상징",
  "TFT16_Item_VoidEmblemItem": "공허 상징",
  "TFT16_Item_YordleEmblemItem": "요들 상징",
  "TFT16_Item_ZaunEmblemItem": "자운 상징",
  "TFT16_Item_SlayerEmblemItem": "학살자 상징",
  "TFT16_Item_Bilgewater_LuckyEyepatch": "행운의 금화",
  "TFT16_Item_Bilgewater_CaptainsBrew": "선장의 비법",
  "TFT16_Item_WardenEmblemItem": "파수꾼 상징",
  "TFT16_Item_IxtalEmblemItem": "이쉬탈 상징",
};
